- name: Check if ~/.ssh directory exists
  stat:
    path: "{{ user.home }}/.ssh/"
  register: ssh_dir

- name: Copy ssh keys to ~/.ssh directory
  copy:
    src: credentials/ssh_keys/
    dest: "{{ user.home }}/.ssh/"
  when: ssh_dir.stat.exists

- name: Check if ~/.aws directory exists
  stat:
    path: "{{ user.home }}/.aws/"
  register: aws_dir

- name: Copy aws credentials to ~/.aws directory
  copy:
    src: credentials/aws/
    dest: "{{ user.home }}/.aws/"
  when: aws_dir.stat.exists

- name: Copy Raycast config to ~/Downloads
  copy:
    src: credentials/raycast/
    dest: "{{ user.home }}/Downloads/"