## SSH keys

- name: Ensure ~/.ssh exists
  file:
    path: "{{ user.home }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ user.name }}"
    group: staff

- name: Install SSH keys (decrypted from vault)
  copy:
    dest: "{{ user.home }}/.ssh/{{ item | basename }}"
    content: "{{ lookup('ansible.builtin.file', item, rstrip=False) }}"
    mode: "{{ '0644' if ((item | basename) | regex_search('(?:\\.pub$|^known_hosts(?:\\.old)?$)')) else '0600' }}"
    owner: "{{ user.name }}"
    group: staff
  with_fileglob:
    - credentials/ssh_keys/*

## AWS credentials

- name: Ensure ~/.aws exists
  file:
    path: "{{ user.home }}/.aws"
    state: directory
    mode: "0700"
    owner: "{{ user.name }}"
    group: staff

- name: Install AWS credentials (decrypted from vault)
  copy:
    dest: "{{ user.home }}/.aws/credentials"
    content: "{{ lookup('ansible.builtin.file', 'credentials/aws/credentials', rstrip=False) }}"
    mode: "0600"
    owner: "{{ user.name }}"
    group: staff

- name: Install Raycast config to ~/Downloads (supports vault)
  copy:
    dest: "{{ user.home }}/Downloads/{{ item | basename }}"
    content: "{{ lookup('ansible.builtin.file', item, rstrip=False) }}"
    mode: "0644"
    owner: "{{ user.name }}"
    group: staff
  with_fileglob:
    - credentials/raycast/*

- name: Ensure ~/.config/goreleaser exists
  file:
    path: "{{ user.home }}/.config/goreleaser"
    state: directory
    owner: "{{ user.name }}"
    group: staff

- name: Install goreleaser GitHub token
  copy:
    dest: "{{ user.home }}/.config/goreleaser/github_token"
    content: "{{ lookup('ansible.builtin.file', 'credentials/goreleaser/github_token', rstrip=False) }}"
    mode: "0600"
    owner: "{{ user.name }}"
    group: staff

- name: Install zsh history (decrypted from vault)
  copy:
    dest: "{{ user.home }}/.zsh_history"
    content: "{{ lookup('ansible.builtin.file', 'credentials/zsh/.zsh_history', rstrip=False) }}"
    mode: "0600"
    owner: "{{ user.name }}"
    group: staff
