---
- name: Install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
  args:
    creates: "{{ nvm_home }}/nvm.sh"

- name: Install latest node version
  shell: "{{ init_nvm }} && nvm install --lts --latest-npm"
  register: nvm_result
  changed_when: "'is already installed' not in nvm_result.stderr"

- name: Set default Node.js to latest LTS
  shell: "{{ init_nvm }} && nvm alias default lts/* && nvm use default"

- name: Gather current Node.js version
  shell: "{{ init_nvm }} && nvm current"
  register: nvm_current

- name: Ensure global node packages are installed
  shell: npm install -g {{ (item.install | default(item.name)) }}
  args:
    creates: "{{ user.home }}/.nvm/versions/node/{{ nvm_current.stdout }}/lib/node_modules/{{ item.name }}"
  with_items: "{{ node_global_packages }}"

# This task is necessary to avoid permission issues when installing global npm packages
- name: Change ownership of .npm directory
  shell: sudo chown -R {{ user.name }}:staff "{{ user.home }}/.npm"

- name: Clean npm cache
  shell: npm cache clean --force
