- name: Make sure ssh agent is running
  shell: eval `ssh-agent -s`

- name: Make Sure ssh folder exists
  stat:
    path: "{{ user.home }}/.ssh"
  register: ssh_folder

- name: Ensure SSH private keys have correct permissions
  file:
    path: "~/.ssh/{{ item }}"
    mode: '0600'
  with_items: "{{ keys }}"
  when: ssh_folder.stat.exists

- name: Add ssh keys to ssh agent
  shell: ssh-add ~/.ssh/{{ item }}
  with_items: "{{ keys }}"
  when: ssh_folder.stat.exists

- name: Copy .gitconfig-personal to ~/Developer/personal/
  copy:
    src: config/.gitconfig-personal
    dest: "{{ user.home }}/Developer/personal/"

- name: Copy .gitconfig-work to ~/Developer/lohum/
  copy:
    src: config/.gitconfig-work
    dest: "{{ user.home }}/Developer/lohum/"
