- hosts: localhost
  become: true
  roles:
    # Shell
    - { role: zsh, tags: "zsh" }

    # Programming languages
    - { role: node, tags: "node" }
    # Go is installed and kept updated via Homebrew (brew "go"), so skip Ansible golang role to avoid duplication

    # Dotfiles
    - { role: stow, tags: "stow" }
    - { role: credentials, tags: "cred" }
    - { role: git, tags: "git" }
