- hosts: localhost
  become: true
  roles:
    # Shell
    - { role: zsh, tags: "zsh" }

    # Programming languages
    - { role: node, tags: "node" }
    - { role: golang, tags: "golang" }

    # Dotfiles
    - { role: stow, tags: "stow" }
    - { role: credentials, tags: "cred" }
    - { role: git, tags: "git" }
